In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [12]:
import pandas as pd

df = pd.DataFrame(digits.data)
df.head()

y = digits.target

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.3)

In [22]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\udaya\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [23]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9907407407407407

In [24]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9666666666666667

Using K-fold method

In [26]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=3) #specifying the no.of folds as 3.
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [34]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):    #Using KFold on simple digits
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


Using a function to return the model score..

In [30]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [31]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

C:\Users\udaya\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [32]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9907407407407407

In [33]:
get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

0.9814814814814815

Using StratifiedKFold, which is also similar to KFold but it classifies the data in a uniform way

In [39]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3) #Usually we should use 10 folds, here in this ex we just used 3 for simplicity.
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [57]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))  #n_estimators is the no.of trees in the random forest classifier.

C:\Users\udaya\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\udaya\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [45]:
scores_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [46]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [58]:
scores_rf

[0.9315525876460768, 0.9549248747913188, 0.9265442404006677]

Since, above piece of code is messy, we have inbuilt sklearn function to do the same as we executed above. Let's see that..!

In [59]:
from sklearn.model_selection import cross_val_score

cross_val_score(LogisticRegression(), digits.data, digits.target)

C:\Users\udaya\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\udaya\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [60]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

cross_val_score(RandomForestClassifier(), digits.data, digits.target) #cross_val_score done the samething as above for loop.

In [63]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93611111, 0.91388889, 0.95543175, 0.9637883 , 0.9275766 ])

Parameter Tuning..

In [64]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.93888889, 0.90277778, 0.9637883 , 0.95264624, 0.92479109])

In [68]:
cross_val_score(RandomForestClassifier(n_estimators=80), digits.data, digits.target)

array([0.93055556, 0.91388889, 0.95264624, 0.95543175, 0.91922006])