In [1]:
import pandas as pd

df = pd.read_csv("spam_ham_dataset.csv")
df.head()

label                                               text  label_num
0   ham  Subject: enron methanol ; meter # : 988291\r\n...          0
1   ham  Subject: hpl nom for january 9 , 2001\r\n( see...          0
2   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...          0
3  spam  Subject: photoshop , windows , office . cheap ...          1
4   ham  Subject: re : indian springs\r\nthis deal is t...          0

In [2]:
df.groupby('label').describe()


label_num                                   
          count mean  std  min  25%  50%  75%  max
label                                             
ham      3673.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
spam     1500.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0

In [3]:
df['spam'] = df['label'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

label                                               text  label_num  spam
0   ham  Subject: enron methanol ; meter # : 988291\r\n...          0     0
1   ham  Subject: hpl nom for january 9 , 2001\r\n( see...          0     0
2   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...          0     0
3  spam  Subject: photoshop , windows , office . cheap ...          1     1
4   ham  Subject: re : indian springs\r\nthis deal is t...          0     0

In [4]:
df

#I'hv used drop function.


label                                               text  label_num  spam
0      ham  Subject: enron methanol ; meter # : 988291\r\n...          0     0
1      ham  Subject: hpl nom for january 9 , 2001\r\n( see...          0     0
2      ham  Subject: neon retreat\r\nho ho ho , we ' re ar...          0     0
3     spam  Subject: photoshop , windows , office . cheap ...          1     1
4      ham  Subject: re : indian springs\r\nthis deal is t...          0     0
...    ...                                                ...        ...   ...
5168   ham  Subject: put the 10 on the ft\r\nthe transport...          0     0
5169   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...          0     0
5170   ham  Subject: calpine daily gas nomination\r\n>\r\n...          0     0
5171   ham  Subject: industrial worksheets for august 2000...          0     0
5172  spam  Subject: important online banking alert\r\ndea...          1     1

[5173 rows x 4 columns]

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.text, df.spam, test_size=0.25)

In [6]:
df.head()

label                                               text  label_num  spam
0   ham  Subject: enron methanol ; meter # : 988291\r\n...          0     0
1   ham  Subject: hpl nom for january 9 , 2001\r\n( see...          0     0
2   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...          0     0
3  spam  Subject: photoshop , windows , office . cheap ...          1     1
4   ham  Subject: re : indian springs\r\nthis deal is t...          0     0

Now, still the data is having text content in the data body. Now, lets try to represent the info in the text column with numerics. This can be achieved by using count vectorizer technique.

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()

array([[0, 2, 0, ..., 0, 0, 0],
       [2, 2, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [8]:
X_train_count

<3879x42572 sparse matrix of type '<class 'numpy.int64'>'
	with 340807 stored elements in Compressed Sparse Row format>

Since the features are having discrete data we should use Multinominal Naive Bayes.

In [9]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count, y_train)

MultinomialNB()

The model has been trained and lets try predicting the output.

In [11]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [13]:
X_test_count = v.transform(X_test) #converting the vector to matrix.
model.score(X_test_count, y_test)

0.9752704791344667

This, conversion of vector to matrix is kinda inconvineance. So, for this there is a feature called pipeline from sklearn which define the pipeline of data.

PIPELINE

In [18]:

from sklearn.pipeline import Pipeline
clf = Pipeline([('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [19]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [20]:
clf.score(X_test,y_test)

0.9752704791344667

In [21]:
clf.predict(emails)

array([0, 1], dtype=int64)